import HSToast from "@/components/HSToast";
import AuthProvider from "@/components/AuthProvider";
import StoreProvider from "@/Redux/StoreProvider";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./global.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <AuthProvider>
                    <StoreProvider>{children}</StoreProvider>
                </AuthProvider>
                <HSToast />
            </body>
        </html>
    );
}
